CREATE TABLE `accounts` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `date_added` DATETIME DEFAULT CURRENT_TIMESTAMP
) CHARSET=utf8mb4;